# Generated by Django 4.0.3 on 2022-04-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admisId', models.IntegerField(primary_key=True, serialize=False)),
                ('admissionTitle', models.CharField(max_length=1000)),
                ('admissionFrom', models.CharField(max_length=200)),
                ('admissionTill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('typename', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=100, null=True)),
                ('fieldDescrib', models.CharField(max_length=20000000, null=True)),
                ('simg', models.ImageField(blank=True, null=True, upload_to='field_image')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('uniId', models.IntegerField(primary_key=True, serialize=False)),
                ('uniName', models.CharField(max_length=200)),
                ('uniaddress', models.CharField(max_length=200)),
                ('uniContact', models.CharField(max_length=13)),
                ('logo', models.ImageField(upload_to='universities')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('couId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseTitle', models.CharField(max_length=200)),
                ('courseDescription', models.TextField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('courseType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultancyapp.coursetype')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultancyapp.studyfield')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultancyapp.university')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDetails',
            fields=[
                ('collegeId', models.IntegerField(primary_key=True, serialize=False)),
                ('collegeImg', models.ImageField(upload_to='colleges')),
                ('collegeLogo', models.ImageField(default='statics/images/album-default.png', null=True, upload_to='colleges')),
                ('collegeName', models.CharField(max_length=200)),
                ('collegeDescription', models.TextField(blank=True, max_length=10000000)),
                ('collegeAddress', models.CharField(blank=True, max_length=200)),
                ('collegecontact', models.CharField(blank=True, max_length=200)),
                ('collegerating', models.IntegerField(blank=True, default=0)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultancyapp.university')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultancyapp.collegedetails')),
                ('couId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultancyapp.coursedetails')),
            ],
        ),
    ]
