# Generated by Django 4.0.3 on 2022-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('s_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_Title', models.CharField(max_length=200)),
                ('s_openFrom', models.CharField(max_length=200)),
                ('s_until', models.CharField(max_length=200)),
                ('s_img', models.ImageField(null=True, upload_to='scholar')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(max_length=200, null=True)),
                ('requirement', models.TextField(blank=True, max_length=100000, null=True)),
                ('info', models.TextField(blank=True, max_length=1000000, null=True)),
            ],
        ),
    ]
