# Generated by Django 3.1.1 on 2022-02-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0002_collegecourse_collegedetails_coursedetails_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='courseDescription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
