# Generated by Django 4.0.3 on 2022-04-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0002_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('c_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_Title', models.CharField(max_length=100)),
                ('c_img', models.ImageField(null=True, upload_to='scholar')),
                ('c_topic', models.CharField(max_length=200, null=True)),
                ('c_requirement', models.TextField(blank=True, max_length=10000, null=True)),
                ('c_info', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('v_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('v_Title', models.CharField(max_length=200)),
                ('v_openFrom', models.CharField(max_length=100)),
                ('v_until', models.CharField(max_length=100)),
                ('v_img', models.ImageField(null=True, upload_to='scholar')),
                ('v_status', models.CharField(blank=True, max_length=100, null=True)),
                ('v_topic', models.CharField(max_length=200, null=True)),
                ('v_requirement', models.TextField(blank=True, max_length=10000, null=True)),
                ('v_info', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='info',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='requirement',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='s_openFrom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='s_until',
            field=models.CharField(max_length=100),
        ),
    ]
