# Generated by Django 4.0.3 on 2022-04-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0003_career_vacancies_alter_scholarship_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('newstitle', models.TextField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True, max_length=100000)),
            ],
        ),
    ]
