# Generated by Django 3.1.1 on 2022-02-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0004_auto_20220214_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedetails',
            name='collegeAddress',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='collegedetails',
            name='collegecontact',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
