# Generated by Django 3.1.1 on 2022-02-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0005_auto_20220214_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetails',
            name='collegeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='couId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
