# Generated by Django 3.1.1 on 2022-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0007_questionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedetails',
            name='collegeLogo',
            field=models.ImageField(blank=True, null=True, upload_to='colleges'),
        ),
        migrations.AddField(
            model_name='collegedetails',
            name='collegerating',
            field=models.IntegerField(blank=True, default=0, max_length=200),
        ),
    ]
