# Generated by Django 3.1.1 on 2022-02-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0007_questionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfield',
            name='simg',
            field=models.ImageField(blank=True, null=True, upload_to='field_image2'),
        ),
    ]
