# Generated by Django 3.1.1 on 2022-02-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0008_auto_20220225_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedetails',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
