# Generated by Django 3.1.1 on 2022-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0009_collegedetails_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetails',
            name='collegeLogo',
            field=models.ImageField(default='statics/images/album-default.png', null=True, upload_to='colleges'),
        ),
    ]
