# Generated by Django 3.1.1 on 2022-02-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0010_auto_20220225_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetails',
            name='collegeDescription',
            field=models.TextField(blank=True, max_length=10000000),
        ),
    ]
