# Generated by Django 3.1.1 on 2022-02-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0011_auto_20220225_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetails',
            name='collegerating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
