# Generated by Django 4.0.3 on 2022-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0012_auto_20220225_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetails',
            name='collegeId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='couId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
