# Generated by Django 4.0.3 on 2022-04-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0014_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admissionFrom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admissionTill',
            field=models.CharField(max_length=200),
        ),
    ]
