# Generated by Django 4.0.3 on 2022-04-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultancyapp', '0018_coursedetails_coursetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('typename', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='courseType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultancyapp.coursetype'),
        ),
    ]
